services:
  - type: web
    name: prime-skin-clinic-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://prime-skin-clinic.onrender.com/api
      - key: VITE_APP_NAME
        value: Prime Skin Clinic
      - key: VITE_APP_VERSION
        value: 1.0.0
    buildFilter:
      paths:
      - client/**
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
